swagger: '2.0'
info:
  description: Retrieve the list of all products or filter by specific criteria
  version: "1.0.0"
  title: Get Products
tags:
  - Products
summary: Retrieve the list of all products
description: Retrieve the list of all products or filter by specific criteria
parameters:
  - name: category_name
    in: query
    type: string
    required: false
    description: Filter products by category name
  - name: category_type
    in: query
    type: string
    required: false
    description: Filter products by category type
  - name: min_price
    in: query
    type: number
    required: false
    description: Filter products by minimum price
  - name: max_price
    in: query
    type: number
    required: false
    description: Filter products by maximum price
  - name: limit
    in: query
    type: integer
    required: false
    description: Limit the number of products returned
  - name: asc_order_by
    in: query
    type: string
    required: false
    description: Order products in ascending order by specefied attribute
  - name: desc_order_by
    in: query
    type: string
    required: false
    description: Order products in descending order by specefied attribute
  - name: from
    in: query
    type: integer
    required: false
    description: Start from this index
  - name: ignore
    in: query
    type: integer
    required: false
    description: Ignore the product with this ID
responses:
  200:
    description: A list of products
    schema:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            example: 4aaa-858e-4e2fdcce-27f7-bde3d87d25d5
          title:
            type: string
            example: Product Title
          price:
            type: number
            example: 19.99
          description:
            type: string
            example: Product description
          category_name:
            type: string
            example: T-shirt
          category_type:
            type: string
            example: Women
          created_date:
            type: string
            format: date-time
            example: 2025-01-01T00:00:00Z
          updated_date:
            type: string
            format: date-time
            example: 2025-01-01T00:00:00Z
          discount:
            type: integer
            example: 10
          img_url:
          type: string
          example: static/images/product-4aaa-858e-4e2fdcce-27f7-bde3d87d25d5
